
version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_INITDB_SKIP_TZINFO: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - frontend

  wordpress:
    build:  ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - frontend
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - wordpress

volumes:
  mariadb_data:
  wordpress_data:

networks:
  frontend:
    driver: bridge
