
version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_INITDB_SKIP_TZINFO: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 5s

  wordpress:
    build:  ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - frontend
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - /home/robert/data/wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - frontend
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/robert/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/robert/data/wordpress

networks:
  frontend:
    driver: bridge
